services:
  frog:
    build: .
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ${DATABASE_PATH:-./daataabaasaa.db}:/app/${DATABASE_PATH:-./daataabaasaa.db}
